In [2]:
import numpy as np
import os,glob,sys

In [7]:
old_manual_positions = [[-4823.30,-1341.10]
                        ,]

new_manual_positions = [[-4821.30, -1342.10],
                        ]

shifts = np.array(new_manual_positions) - np.array(old_manual_positions)
print(shifts)
# calculate mean
manual_shift = np.round(np.mean(shifts, axis=0), 2)
print(manual_shift)

[[ 2. -1.]]
[ 2. -1.]


In [8]:
data_folder = r'D:\Shiwei\20240119-RPE1_CTP14_genome_Tn5_exp2'
old_positions = np.loadtxt(os.path.join(data_folder, 'positions_all.txt'), delimiter=',')

In [9]:
print(old_positions)

[[-4825.4 -1343.9]
 [-4825.4 -1138.9]
 [-4825.4  -933.9]
 [-4825.4  -728.9]
 [-4825.4  -523.9]
 [-4825.4  -318.9]
 [-4825.4  -113.9]
 [-4825.4    91.1]
 [-4620.4   296.1]
 [-4620.4    91.1]
 [-4620.4  -113.9]
 [-4620.4  -318.9]
 [-4620.4  -523.9]
 [-4620.4  -728.9]
 [-4620.4  -933.9]
 [-4620.4 -1138.9]
 [-4620.4 -1343.9]
 [-4620.4 -1548.9]
 [-4620.4 -1753.9]
 [-4415.4 -1753.9]
 [-4415.4 -1548.9]
 [-4415.4 -1343.9]
 [-4415.4 -1138.9]
 [-4415.4  -933.9]
 [-4415.4  -728.9]
 [-4415.4  -523.9]
 [-4415.4  -318.9]
 [-4415.4  -113.9]
 [-4415.4    91.1]
 [-4415.4   296.1]
 [-4210.4   296.1]
 [-4210.4    91.1]
 [-4210.4  -113.9]
 [-4210.4  -318.9]
 [-4210.4  -523.9]
 [-4210.4  -728.9]
 [-4210.4  -933.9]
 [-4210.4 -1138.9]
 [-4210.4 -1343.9]
 [-4210.4 -1548.9]
 [-4210.4 -1753.9]
 [-4005.4 -1753.9]
 [-4005.4 -1548.9]
 [-4005.4 -1343.9]
 [-4005.4 -1138.9]
 [-4005.4  -933.9]
 [-4005.4  -728.9]
 [-4005.4  -523.9]
 [-4005.4  -318.9]
 [-4005.4  -113.9]
 [-4005.4    91.1]
 [-4005.4   296.1]
 [-3800.4   

In [10]:
adjusted_positions = old_positions + manual_shift

In [11]:
adj_save_filename = os.path.join(data_folder, 'adjusted_positions_all.txt')
print(adj_save_filename)
np.savetxt(adj_save_filename, adjusted_positions, fmt='%.2f', delimiter=',')

D:\Shiwei\20240101-RPE1_CTP14_genome_Tn5\adjusted_positions_all.txt


In [12]:
adjusted_positions

array([[-4823.4, -1344.9],
       [-4823.4, -1139.9],
       [-4823.4,  -934.9],
       [-4823.4,  -729.9],
       [-4823.4,  -524.9],
       [-4823.4,  -319.9],
       [-4823.4,  -114.9],
       [-4823.4,    90.1],
       [-4618.4,   295.1],
       [-4618.4,    90.1],
       [-4618.4,  -114.9],
       [-4618.4,  -319.9],
       [-4618.4,  -524.9],
       [-4618.4,  -729.9],
       [-4618.4,  -934.9],
       [-4618.4, -1139.9],
       [-4618.4, -1344.9],
       [-4618.4, -1549.9],
       [-4618.4, -1754.9],
       [-4413.4, -1754.9],
       [-4413.4, -1549.9],
       [-4413.4, -1344.9],
       [-4413.4, -1139.9],
       [-4413.4,  -934.9],
       [-4413.4,  -729.9],
       [-4413.4,  -524.9],
       [-4413.4,  -319.9],
       [-4413.4,  -114.9],
       [-4413.4,    90.1],
       [-4413.4,   295.1],
       [-4208.4,   295.1],
       [-4208.4,    90.1],
       [-4208.4,  -114.9],
       [-4208.4,  -319.9],
       [-4208.4,  -524.9],
       [-4208.4,  -729.9],
       [-4208.4,  -934.9],
 